apiVersion: v1
kind: Service
metadata:
  name: {{ include "clickhouse.fullname" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: native
      port: {{ .Values.service.nativePort }}
      targetPort: native
      protocol: TCP
  selector:
    {{- include "clickhouse.selectorLabels" . | nindent 4 }}
