apiVersion: v2
name: metrics-server
description: Metrics Server for local k3d cluster
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: metrics-server
    version: "3.12.2"
    repository: https://kubernetes-sigs.github.io/metrics-server/
